name: CICD workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: install up Poetry
        run: |
          python -m pip install --upgrade pip 
          pip install poetry

      - name: install dependencies in venv
        run: poetry install

      - name: run unit tests
        run: poetry run python -m pytest

        
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: install up Poetry
        run: |
          python -m pip install --upgrade pip 
          pip install poetry

      - name: install dependencies in venv
        run: poetry install

      - name: runs type checking
        run: poetry run python -m mypy .
