
name: CICD workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Python/Poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python -m pip install --upgrade pip 
      - run: pip install poetry

      - name: install dependencies in venv
      - run: poetry init --no-interaction
      - run: poetry add --no-interaction --dev pytest mypy
      - run: poetry add --no-interaction petl
      - run: poetry install

      - name: run unit tests
      - run: poetry run python -m pytest
